import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Make sure this exists in the right location
import Logocart from "@/app/components/logoWithCartButton";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/header"
const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Header />
        <Logocart />
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
